DROP TABLE "ALLERGEN" CASCADE CONSTRAINTS;
DROP TABLE "BROKER" CASCADE CONSTRAINTS;
DROP TABLE "CUISINE" CASCADE CONSTRAINTS;
DROP TABLE "COMPLAINT" CASCADE CONSTRAINTS;
DROP TABLE "DONEE" CASCADE CONSTRAINTS;
DROP TABLE "DONEE_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "DONEE_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "DONEE_PRICE_RANGE" CASCADE CONSTRAINTS;
DROP TABLE "DONEE_SPICE_RANGE" CASCADE CONSTRAINTS;
DROP TABLE "DONOR" CASCADE CONSTRAINTS;
DROP TABLE "DONOR_STATUS" CASCADE CONSTRAINTS;
DROP TABLE "ERROR_LOG" CASCADE CONSTRAINTS;
DROP TABLE "FOOD" CASCADE CONSTRAINTS;
DROP TABLE "MAP_DONEE_ALLERGEN" CASCADE CONSTRAINTS;
DROP TABLE "MAP_DONEE_CUISINE" CASCADE CONSTRAINTS;
DROP TABLE "MAP_DONEE_MEAL_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "MAP_FOOD_ALLERGEN" CASCADE CONSTRAINTS;
DROP TABLE "MAP_FOOD_CUISINE" CASCADE CONSTRAINTS;
DROP TABLE "MAP_FOOD_MEAL_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "MAP_PERSON_ROLE" CASCADE CONSTRAINTS;
DROP TABLE "MEAL_TYPE" CASCADE CONSTRAINTS;
DROP TABLE "PERSON" CASCADE CONSTRAINTS;
DROP TABLE "PERSON_ROLE" CASCADE CONSTRAINTS;
DROP TABLE "REQUEST" CASCADE CONSTRAINTS;
DROP TABLE "SUB_REQUEST" CASCADE CONSTRAINTS;
DROP TABLE "SPICE_LEVEL" CASCADE CONSTRAINTS;



